#!/usr/bin/env bash
# secrets.sh — manage app secrets in SSM Parameter Store.
#
# The app's runtime configuration (SMTP, LLM keys, scope, scheduler time, …) is
# stored as SecureString parameters under /property-hunter/*. The on-instance
# deploy script fetches them and writes the app's .env. No secret ever lives in
# the repository.

set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

# shellcheck source=scripts/cloud/lib.sh
. scripts/cloud/lib.sh

PATH_PREFIX="/property-hunter"
ENV_FILE=".env"
FORCE=0
REGION=""

usage() {
  cat <<'EOF'
Usage: scripts/cloud/secrets.sh <push|pull|list> [options]

Manage the app's SSM SecureString parameters under /property-hunter/*.

Subcommands:
  push               Read the local .env and write each key to SSM (idempotent)
  pull               Fetch all /property-hunter/* params and write the local .env
  list               List parameter names (never values)

Options:
  --env-file <path>  .env to read/push or write/pull (default: .env)
  --force            Overwrite an existing local .env on pull
  --path <prefix>    SSM path prefix (default: /property-hunter)
  --region <region>  AWS region (default: AWS CLI default)
  --help             Show this help and exit

Exit codes: 0 success, 1 expected failure, 2 tooling/environment error.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    push|pull|list) CMD="$1"; shift ;;
    --env-file) ENV_FILE="${2:?--env-file needs a value}"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --path) PATH_PREFIX="${2:?--path needs a value}"; shift 2 ;;
    --region) REGION="${2:?--region needs a value}"; shift 2 ;;
    --help) usage; exit 0 ;;
    *) fail "unknown option: $1 (try --help)" ;;
  esac
done

[ -n "${CMD:-}" ] || fail "missing subcommand (push|pull|list) — try --help"
require aws "AWS CLI v2 is required"
require python3 "python3 is required"

REGION_ARGS=()
[ -n "$REGION" ] && REGION_ARGS=(--region "$REGION")

case "$CMD" in
  push)
    [ -f "$ENV_FILE" ] || fail "no .env file found at '$ENV_FILE' (copy .env.cloud.example)"
    echo "==> Pushing secrets from $ENV_FILE to ${PATH_PREFIX}/*"
    python3 - "$ENV_FILE" "$PATH_PREFIX" <<'PY' | while IFS=$'\t' read -r name value; do
import json, os, sys
path = sys.argv[1]; prefix = sys.argv[2]
import re
try:
    from dotenv import dotenv_values
except ImportError:
    dotenv_values = None
if dotenv_values:
    values = dotenv_values(path)
else:  # minimal fallback parser
    values = {}
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        values[k.strip()] = v.strip().strip('"').strip("'")
for k, v in values.items():
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", k):
        continue
    print(f"{prefix}/{k}\t{v}")
PY
      [ -n "$name" ] || continue
      aws ssm put-parameter --name "$name" --type SecureString --value "$value" --overwrite \
        "${REGION_ARGS[@]}" >/dev/null || die "failed to write $name"
      echo "  wrote $name"
    done
    echo "==> Secrets pushed (${PATH_PREFIX}/*)"
    ;;

  pull)
    if [ -e "$ENV_FILE" ] && [ "$FORCE" -eq 0 ]; then
      fail "refusing to overwrite existing '$ENV_FILE' (use --force)"
    fi
    echo "==> Pulling secrets from ${PATH_PREFIX}/* to $ENV_FILE"
    aws ssm get-parameters-by-path --path "$PATH_PREFIX" --with-decryption --recursive \
      "${REGION_ARGS[@]}" --output json > /tmp/ph-secrets.json || die "failed to fetch parameters"
    python3 - "$ENV_FILE" "$PATH_PREFIX" <<'PY'
import json, sys
out, prefix = sys.argv[1], sys.argv[2]
data = json.load(open("/tmp/ph-secrets.json"))["Parameters"]
lines = []
for p in sorted(data, key=lambda x: x["Name"]):
    key = p["Name"].rsplit("/", 1)[-1]
    value = p["Value"]
    if "\n" in value:
        value = '"' + value.replace("\n", "\\n") + '"'
    lines.append(f"{key}={value}")
with open(out, "w") as f:
    f.write("# Generated by scripts/cloud/secrets.sh pull — values are git-ignored.\n")
    f.write("\n".join(lines) + "\n")
print(f"wrote {len(lines)} keys to {out}")
PY
    ;;

  list)
    aws ssm get-parameters-by-path --path "$PATH_PREFIX" --recursive \
      "${REGION_ARGS[@]}" --query "Parameters[].Name" --output text \
      | tr '\t' '\n' | sed '/^$/d'
    ;;
esac
